@startuml

skinparam linetype ortho
'skinparam groupInheritance 3
'skinparam handwritten true
hide circle

skinparam participant{
    BorderColor darkgreen
    BackgroundColor white
    FontStyle bold
}

skinparam arrow{
    Color darkgreen
}

skinparam sequence{
    LifeLineBorderColor black
}

Customer -> Staff: buys milk in a bottle
activate Staff
activate Customer
ShoppingCart <- Staff: add milk
activate ShoppingCart
ShoppingCart -> Product: Price Request
activate Product
ShoppingCart <- Product: Price Response
ShoppingCart -> Product: Category Request
ShoppingCart <- Product: Category Response
deactivate Product
ShoppingCart -> Staff: successfully added product
Customer -> Staff: gives empty bottle
Staff -> ShoppingCart: add empty bottle
ShoppingCart -> Product: Price Request
activate Product
ShoppingCart <- Product: Price Response
ShoppingCart -> Product: Category Request
ShoppingCart <- Product: Category Response
deactivate Product
ShoppingCart -> Staff: successfully added product
Customer <- Staff: Id Request
Customer -> Staff: Id Response
Staff -> CashierSystem: enters id
activate CashierSystem
Staff -> CashierSystem: Scan finished
CashierSystem -> ShoppingCart: Product Request
CashierSystem <- ShoppingCart: Product Response
deactivate ShoppingCart
CashierSystem -> CashierSystem: Sum of base prices
activate CashierSystem
CashierSystem -> CashierSystem: Calculate with discount
activate CashierSystem
CashierSystem -> CashierSystem: Calculate with MwSt.
activate CashierSystem
CashierSystem -> CashierSystem: add/substract Pfand
activate CashierSystem
deactivate CashierSystem
deactivate CashierSystem
deactivate CashierSystem
deactivate CashierSystem
deactivate CashierSystem

@enduml