@startuml

skinparam linetype ortho
'skinparam groupInheritance 3
'skinparam handwritten true
hide circle

skinparam participant{
    BorderColor darkgreen
    BackgroundColor white
    FontStyle bold
}

skinparam arrow{
    Color darkgreen
}

skinparam sequence{
    LifeLineBorderColor black
}

Manager -> UserList: add Customer
'For Major Customer
activate Manager
activate UserList
Manager <- UserList: Request type customer
Manager -> UserList: Response type customer
UserList -> Person: Add new person
Person -> UserList: Request name
UserList -> Manager: Request name
UserList <- Manager: Response name
UserList -> Person: Response name
Person -> UserList: Request address
UserList -> Manager: Request address
UserList <- Manager: Response address
UserList -> Person: Response address
Person -> UserList: Request email
UserList -> Manager: Request email
UserList <- Manager: Response email
UserList -> Person: Response email
Person -> UserList: Request phoneNr
UserList -> Manager: Request phoneNr
UserList <- Manager: Response phoneNr
UserList -> Person: Response phoneNr
Person -> UserList: gets added as a new user

@enduml