= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2017/18
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von: Lisa Riedel**

**Gruppe: 43**

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Arbeiten mit großen Frameworks. (und Java)

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Mit dem meisten Teammitgliedern eine gute Zusammenarbeit. Jedoch gab es da auch ein "schwarzes" Loch, wo man kein Stand wusste, erst dann Sonntag 23 Uhr gefragt wurde ob einer nicht noch helfen könnte, damit es ja noch "pünktlich" zur Abgabe fertig ist.
Damit war teilweise die Arbeit nur auf 4 statt 5 Personen aufteilbar (siehe z.B Git-Statistic), was einen selbst ziemlich viel Zeitaufwand brachte.
kurz: TEAM - Toll Ein Anderer Machts

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Das Reinarbeiten in die Frameworks war am Anfang schwer, nach einer Zeit ging es besser, da man auch sich an den Videoshop mit orientieren konnte und ich dadurch einige Dinge verstanden habe.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Zeitaufwand in einigen Wochen sehr hoch, in der ersten Woche dafür sehr gering, weil man nicht wirklich schon was machen kann.

Jedes Gruppenmitglied sollte einzeln bewertet werden, da sich sonst einige Mitglieder durchziehen lassen können auf kosten der Anderen.
Denn wenn jemand sich nicht an Absprachen etc. leidet auch die eigene Bewertung drunter.
Vielleicht könnte man auch das Punktesystem, was die Tutoren haben um dem Umfang/Arbeitsaufwandes des Projektes mit nutzen, da es auch unfair ist, wenn man viel mehr macht (damit es Termin gerecht fertig ist) und andere Mitglieder nur das nötigste machen bzw auch spät ihr Zeug pushen und damit es nicht gleichmäßig aufgeteilt werden kann.
Damit könnte man dafür sorgen, dass man kaum was machen muss um das Projekt zu bestehen (und das zu Leiden der anderen Gruppenmitglieder darunter verringern).
Die Punktzahl aus dem Elementen, was man gemacht hat sind aussagekräftiger als die Zeit, da einige viel/weniger Zeit für manche Dinge brauchen (das ist ja normal).

Wäre schön wenn SonarQube auf dem develop auch bauen würde.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich finde, dass unser Tutor uns gut betreut hat, jedoch wäre noch schön gewesen, wenn er mehr auf die Gleichverteilung der Aufgaben bzw. Arbeitsanteile geachtet hätte.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
Die Templates für z.B Pflichtenheft sollten genauer Beschrieben werden. Einige Punkte waren sehr schwammig formuliert. Zur Dialoglandkarte konnte man leider auch nichts in dem Vorlesung- oder Übungsmaterial finden.