@startuml
hide circle


class Person{
    name
    adresse
    email
    phoneNr
}

class Staff{
    '== attributes =='
    username
    password

    '=== methods ===='
    login()
}

class Distributor{
    '== attributes =='
    companyname
    address
    contactPartner
    minimumOrderQuantity
    paymentMethods
    taxNumber
}

class Customer{
    preferences
    discount
    getCatalog()
}

class Manager{
    resetLogin()
    addLogin()
    orderProducts()
}


Customer ^-- Staff
Person ^-- Customer


Staff ^-- Manager
Staff ^-- SalesStaff

Customer ^-- NormalCustomer
Customer ^-- HouseCustomer
Customer ^-- MajorCustomer


class Product{
    '== attributes =='
    description
    bnnInfo
    ean
    quantityStored
    quantityDisplayed

}

class ProductList{

}

Product -left- ProductList

@enduml