@startuml
skinparam linetype ortho
'skinparam groupInheritance 3
'skinparam handwritten true
hide circle

skinparam class {
	'BackgroundColor Lavender
	BackgroundColor #GreenYellow/LightGoldenRodYellow
    BorderColor Black
    ArrowColor  Black
}

skinparam package {
    FontColor Grey
    BorderColor Green
    shadowing false
}

class Database{
    sort()
    add()
    delete()
    search()
}

package UserResort {

class CustomerList{
    addCustomer()
    deleteCustomer()
    setCustomerPermissions()
}

class Person{
    name
    adresse
    email
    phoneNr
}


class Customer{
    preferences
    discount
    id
    permissions
    getCatalog()
    setDiscount()
    getDiscount()
}

class Manager{
    resetLogin()
    addLogin()
    orderProducts()
}


Person ^-- Customer


Staff ^-- Manager
Staff ^-- SalesStaff

Customer ^-- NormalCustomer
Customer ^-- HouseCustomer
Customer ^-- MajorCustomer
Customer ^-- Staff


class Staff{
    '== attributes =='
    username
    password

    '=== methods ===='
    login()
}

Manager "1" --> "1" Calendar
CustomerList "1" -- "0..*" Customer
Database ^-- CustomerList

}









class Calendar{
    addAppointment()
    editAppointment()
    deleteAppointment()
}







package ProductResort{
    class Product{
        '== attributes =='
        description
        bnnInfo
        ean
        quantityStored
        quantityDisplayed
        price

        getPrice()
        getProductInfo()

    }

    class ProductList{
        addProduct()
        deleteProduct()
    }

    class DistributorList{

    }

    class OrderableProducts{

    }

    class LabelGenerator{
        printLabelAll()
        printLabelProduct()
        generateBarCode()
    }

    class Distributor{
        '== attributes =='
        companyName
        address
        contactPartner
        minimumOrderQuantity
        paymentMethods
        taxNumber
    }

    OrderableProducts "1" -left-o "1" DistributorList
    DistributorList "1" o-- "0..*" Distributor

    Database ^-- DistributorList




    ProductList -up-^ Database
    ProductList "1" o-- "0..*" Product
    Product "1..*" *-- "1" LabelGenerator
    ProductList ^-- OrderableProducts

    Product "1..*" *-- "1" Distributor

    package InventoryResort{

        class Order{
            id
            arrived
            content

            placeContentInInventory()
        }

        class OrderAssistant{
            getLowestPriceForProduct()
            order()
        }

        class Inventory {
            profitValue

            setProfitValue()
            getProfitValue()
            getValueOfStoredProducts()
        }

        Order -up-> Inventory
        OrderableProducts <-- OrderAssistant
        ProductList ^-- Inventory
        OrderAssistant <-- Manager

    }

}

package DataResort {

    class Statistic{
        sales
        purchases
        time
        soldWares
        purchasedWares
        stolenProducts

        getStatics()
    }

    class Log{
        getSales()
        getPurchases()
        getTime()
        getSoldWares()
        getPurchasedWares()
        getCustomerPreferences()
        getStolenProducts()
    }

    Log "1" *-left- "1" Statistic


    Log -right-> Customer


}

rectangle FinancesResort {
    class CashRegister{
        calculatePrice()
        giveChange()
        cancelAll()
        cancelProduct()
        enterCustomerId()

    }




    class ShoppingCart{
        addProduct()
        deleteProduct()
    }

    Log <-- CashRegister

    CashRegister "1" *-down- "1" ShoppingCart
    ShoppingCart "1" --* "1..*" Product



}

@enduml