@startuml
skinparam componentStyle uml2
'skinparam linetype ortho
'skinparam handwritten true
skinparam componentStyle uml2



component [ShopManagementSystem] <<component>> as proc
rectangle "Manager" as k1
rectangle "Staff" as k2
rectangle "NormalCustomer" as k3
rectangle "HouseCustomer" as k4
rectangle "Major Customer" as k5

proc #-0)- k2

proc #-0)- k1

proc #-0)- k3

proc #-0)- k4

proc #-0)- k5


@enduml