@startuml
skinparam componentStyle uml2
'skinparam linetype ortho
'skinparam handwritten true
skinparam componentStyle uml2

skinparam rectangle {
    fontStyle bold
	BackgroundColor #GreenYellow/LightGoldenRodYellow

}

skinparam component {
    fontStyle bold
	BackgroundColor #GreenYellow/LightGoldenRodYellow
    BorderColor darkgreen
}

skinparam Arrow {
    Color darkgreen
}




component [Bioladen] <<component>> as proc

rectangle "Manager" as k1
rectangle "Staff" as k2
rectangle "NormalCustomer" as k3
rectangle "HouseCustomer" as k4

proc #-0)- k2: add NormalCustomer,\noperate cash register

proc #-0)- k1: order Products, \nadd all Customers, \nchange database entries

proc #-0)- k3: take products and \ngive money

proc #-0)- k4: take products and \ngive money



@enduml