@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor blue
skinparam titleBackgroundColor Chartreuse
'skinparam handwritten true
skinparam groupInheritance 3
skinparam linetype ortho



title Anwendungsfall - Diagramm


' === Kunden === '
:Kunde: as ku
:Normalkunde: as nku
:Großhandelsabnehmer: as gha
:Hauskunde: as hku

'left to right direction

' === Personal === '
:Verkaufspersonal: as vp
:Geschäftsleitung: as gl

nku --> ku
vp --> ku
gha --> ku
hku --> ku

' === Sonstiges === '
database "System" as sys

' === Y === '
rectangle "coole Box"{
    (Inventur) as inv
    '(Pfand auszahlen)

    (Account erstellen) as acc
    (Termin eintragen) as date
    
    (Produkt tauschen)
    (Großkundendatenbank\nimportieren) as grokudb_imp
    (Verkaufspreis kalkulieren) as vp_calc
    (Eingabe von\nNormalkundendaten) as eg_nkd
    (Etikett drucken) as et_dr
    (Bestellvorgang erfassen)
    (Waren und/oder Geldbewegung\narchivieren)
    (Stornierung archivieren)
    (Ware einkaufen)
    (günstigsten Anbieter wählen) as gaw
    (Warenscanvorgang abschließen)
    



    package "Kassensystem"{
            (Bargeld einzahlen) as bg_ez
            (Bargeld auszahlen) as bg_az
            (Bargeld wechseln) as bg_we
            (Wechselgeld berechnen) as we_br

            (einfache Stornierung) as l_st
            (globale Stornierung) as g_st

            (Artikel zu Warenkorb hinzufügen) as azw

            vp -- Kassensystem

            gl -- date
            gl -- acc



            ku -- bg_ez

            'vp -- bg_we
            'vp -- bg_az
            'vp -- l_st


            sys -- we_br

            bg_ez <.. bg_we: <<include>>
            bg_ez <.. bg_az: <<include>>
            bg_az ..> we_br: <<include>>
            bg_we ..> we_br: <<include>>
            we_br ..> bg_ez: <<include>>
            l_st <.. g_st: <<extend>>
            l_st ..> azw: <<include>>

        }

    package --- {
        :i_i_i_i: as a
        a .. a
    }


    '



    '
    vp -- inv
    vp -- et_dr
    vp -- eg_nkd



    '
    gl -- grokudb_imp

    '
    sys -- vp_calc





}

@enduml
