@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor blue
skinparam titleBackgroundColor Chartreuse
'skinparam handwritten true
'skinparam groupInheritance 3
skinparam linetype ortho

skinparam package {
    FontColor Grey
    BorderColor Green
    shadowing false
}

title Anwendungsfall - Diagramm


' === Kunden === '
:Kunde: as ku
:Normalkunde: as nku
:Großhandelsabnehmer: as gha
:Hauskunde: as hku

left to right direction

' === Personal === '
:Verkaufspersonal: as vp
:Geschäftsleitung: as gl

nku --> ku
vp --> hku
gha --> hku
hku --> ku

' === Sonstiges === '
database "System" as sys

' === Y === '
'rectangle "coole Warenwirtschaftssystembox"{
    '(Pfand auszahlen)

    package "Accountverwaltung"{
        (Account erstellen) as acc
        (Account löschen) as accdel

    }

    (Termin eintragen) as date
    
    (Etikett drucken) as et_dr
        (Waren und/oder Geldbewegung\narchivieren)
    (Stornierung archivieren)




    package "Kassensystem"{
            (Barzahlung) as bg_ez
            (Rückgeld geben) as bg_az
            (Wechselgeld berechnen) as we_br
            (Summenberechnung der Grundpreise) as sdg
            (Rabattberechnung) as rab
            (Mehrwehrtsteuerberechnung) as mwst
            (Endpreis ausgeben) as epa

            (einfache Stornierung) as l_st
            (globale Stornierung) as g_st

            (Artikel zu Warenkorb hinzufügen) as azw
            (Produkt einscannen) as scan

            vp -- Kassensystem

            gl -- date
            gl -- acc
            gl -- accdel

            gl --> vp


            ku -- bg_ez

            'vp -- bg_az
            'vp -- l_st


            sys -- we_br

            bg_ez <.. bg_az: <<include>>
            bg_az ..> we_br: <<include>>
            we_br ..> bg_ez: <<include>>
            l_st <.. g_st: <<extend>>
            l_st ..> scan: <<include>>
            azw ..> scan: <<include>>
            sdg ..> azw: <<include>>
            rab ..> sdg: <<include>>
            mwst ..> rab: <<include>>
            epa ..> mwst: <<include>>




        }

    'package --- {
    '    :i_i_i_i: as a
    '    a .. a
    '}


    package "Inventur"{
        (Bestand erfassen)
        (abweichenden Bestand festgestellt) as abf
        (Manager benachrichtigen) as glb
        (Bestand berichtigen) as bb

        sys -- abf
        sys -- glb
        gl -- bb
    }


    package "Bestellung"{
        (Bestellung abschicken) as ba
        (günstigsten Preis finden) as gpf
        (Bestellung erstellen) as bers
        (Bestellung empfangen) as bempf
        (Bestellung inventarisieren) as binvent

        gpf <.. bers: <<include>>
        ba <.. gpf: <<include>>
        bempf <.. binvent: <<include>>
        sys -- binvent
    }


    package "Händlerverwaltung"{
        (Händler hinzufügen)
        (Händler löschen)
        (Händlerdaten bearbeiten)

        gl -- Händlerverwaltung
    }

    package "Produktverwaltung"{
        (Produkt hinzufügen)
        (Produkt löschen)
        (Produktdaten bearbeiten)
        (Großhändlerproduktbestellliste \nimportieren)
        (Produkt zur Verkaufsdatenbank hinzufügen)
        (Produkt von der Verkaufsdatenbank löschen)

        gl -- Produktverwaltung
    '}








}

@enduml
