@startuml

skinparam class {
	BackgroundColor #LightCoral/LightPink
    BorderColor Black
    ArrowColor  Black
}

skinparam package {
    FontColor Grey
    BorderColor DarkMagenta
}

skinparam classAttributeIconSize 0
skinparam linetype ortho



rectangle salespoint-framework-7.0.0.RELEASE.jar {

    namespace org.salespointframework.catalog {
        interface Catalog <T extends Product> <<Repository>> {

        }

        class Product <<Entity>> {
            -productIdentifier : ProductIdentifier
            -name : String
            -price : MonetaryAmount
            -categories : Set<String>
            -metric : Metric

            +Product(String, MonetaryAmount)
            +Product(String, MonetaryAmount, Metric)
            +getId() : ProductIdentifier
            +getCategories() : Streamable<String>
            +addCategory(String) : boolean
            +removeCategory(String) : boolean
            +supports(Quantity) : boolean
            +verify(Quantity) : void
            +createQuantity(double) : Quantity
            +createQuantity(long) : Quantity

        }

    }

    package org.salespointframework.time {
        interface BusinessTime <<Service>> {

        }
    }

    namespace org.salespointframework.context {
            class ApplicationEvent {

            }

        }

}


rectangle spring-data-comments-2.1.0.RELEASE.jar as spring {

    namespace org.springframework.data.repository {
        interface CrudRepository <T, ID>{
            <S extends T> +save(S) : S
            <S extends T> +saveAll(Iterable<S​>) : Iterable<S>
            +findById(ID) : Optional<T>
            +existsById(ID) : boolean
            +findAll() : Iterable<T>
            +findAllById(Iterable<ID>) : Iterable<T>
            +count() : long
            +deleteById(ID) : void
            +delete(T) : void
            +deleteAll(Iterable<? extends T>) : void
            +deleteAll() : void
        }
    }
}

rectangle Bioladen {

    namespace bioladen.product {

        interface ProductCatalog <<Repository>> {
            +findBy(Product) : Streamable<Product>
        }

        interface DistributorProductCatalog <<Repository>> {
            +findBy(DistributorProduct) : Streamable<DistributorProduct>
        }

        class DistributorProduct <<Entity>> extends org.salespointframework.catalog.Product {
            -id : ProductIdentifier
            -unit : Quantity
            -distributor : Distributor
            -minimumOrderAmount : Amount

            +getUnit() : Unit
            +getInventoryAmount() : Amount
            +getDisplayedAmount() : Amount
            +setUnit(Quantity) : void
            +setInventoryAmount(Amount) : void
            +setDisplayedAmount(Amount) : void
            +setPrice(MonetaryAmount) : void
        }

        class Product <<Entity>> {
            -unit : Quantity
            -inventoryAmount : Amount
            -displayedAmount : Amount
            -distributorProducts : List<DistributorProducts>

            +getUnit() : Unit
            +getInventoryAmount() : Amount
            +getDisplayedAmount() : Amount
            +setUnit(Quantity) : void
            +setInventoryAmount(Amount) : void
            +setDisplayedAmount(Amount) : void
            +setPrice(MonetaryAmount) : void
            +verify() : boolean
            +getPrice() : MonetaryAmount
        }

        class Distributor <<Entity>> {
            -name : String
            -email : String
            -contactName : String
            -phoneNr : String

            +publishDistributorCreatedEvent(Distributor) : void
         }




        Product  o--  DistributorProduct
        DistributorProduct  --* "1" DistributorProductCatalog
        Product --* "1" ProductCatalog


    }

    namespace bioladen.event {
        class EntityCreatedEvent {

        }
        EntityCreatedEvent --|> org.salespointframework.context.ApplicationEvent
    }


    package bioladen.product.web {
        class CatalogController <<Controller>> {

        }
    }

    namespace Amount {
        class Amount {
            +of(long) : Amount

        }
        Amount <-- bioladen.product.Product
        Amount <-- bioladen.product.DistributorProduct
    }





}

bioladen.product.Distributor --> bioladen.event.EntityCreatedEvent

CatalogController "1" *-- "1" bioladen.product.ProductCatalog
CatalogController "1" *-- "1" bioladen.product.DistributorProductCatalog
CatalogController --> BusinessTime
org.salespointframework.catalog.Catalog --|> org.springframework.data.repository.CrudRepository: <<binds>>\n<T, ProductIdentifier>
org.salespointframework.catalog.Catalog <|-- bioladen.product.ProductCatalog: <<binds>>\n<Product>
org.salespointframework.catalog.Catalog <|-- bioladen.product.DistributorProductCatalog: <<binds>>\n<DistributorProduct>
bioladen.product.Distributor "1" *--  bioladen.product.DistributorProduct

@enduml