@startuml

!include stylesheet.iuml

rectangle salespoint-framework-7.0.0.RELEASE.jar {

    namespace org.salespointframework.useraccount {
        class UserAccount <<Salespoint>> {
            -userAccountIdentifier : UserAccountIdentifier
            -password : Password
            -firstname : String
            -lastname : String
            -email : String
            -roles : Set<Role>
            -enable : boolean

            +UserAccount()
            +UserAccount(UserAccountIdentifier, String, Role...)
            +UserAccount(UserAccountIdentifier, String, String, String, String, Collection<Role>)
            +getID() : UserAccountIdentifier
            +getUserName() : String
            +add(Role) : boolean
            +remove(Role) : boolean
            +hasRole() : boolean
            +getRoles() : Streamable<Role>
        }

        class Role <<Salespoint>>{
            -name : String

            +{static} of(String) : Role
        }

        interface UserAccountRepository <<Salespoint>> {
            +save(UserAccount) : UserAccount
            +saveAll(Iterable<UserAccount>) : Iterable<UserAccount>
            +findById(UserAccountIdentifier) : Optional<UserAccount>
            +existsById(UserAccountIdentifier) : boolean
            +findAll() : Iterable<UserAccount>
            +findAllById(Iterable<UserAccountIdentifier>) : Iterable<UserAccount>
            +count() : long
            +deleteById(UserAccountIdentifier) : void
            +delete(UserAccount) : void
            +deleteAll(Iterable<UserAccount>) : void
            +deleteAll() : void
            +findByEnabledTrue() : Streamable<UserAccount>
            +findByEnabledFalse() : Streamable<UserAccount>
        }

        interface UserAccountManager <<Salespoint>>

    }

    namespace org.salespointframework.context {
        class ApplicationEvent <<Salespoint>>{

        }

    }

    package org.salespointframework.time {
        interface BusinessTime <<Salespoint>> {

        }
    }

}



rectangle Bioladen {

    namespace bioladen.useraccount {

        class UserAccountController <<Controller>>  {
            +login(LoginForm) : User
            +logout(LogoutForm) : boolean
            +resetPassword(ResetForm) : boolean
            +createUser(UserForm) : boolean
            +deleteUser(UserForm) : boolean
            +searchUser(SearchForm) : List<User>
            +setNewPassword(SetForm) : boolean

        }

        class UserAccount <<Entity>> {

        }

        class Customer <<Entity>> {
            -firstname : String
            -lastname : String
            +enum sex {M, W, D}
            -email : String
            -phoneNumber : String
            +enum type {MANAGER, PERSONAL, GROSSKUNDE, HAUSKUNDE}
            -id : CustomerIdentifier
            -userAccount : UserAccount
            publishCustomerCreatedEvent(Customer) : void

        }

         class CustomerIdentifier {
            CustomerIdentifier() : void
            CustomerIdentifier(String) : void
         }

        class UserAccountWrapper {
            UserAccountWrapper(Customer) : UserAccount
        }

        interface CustomerRepository <<Repository>> {

        }

        UserAccount --* Customer
        Customer --> CustomerIdentifier
        UserAccountWrapper --> org.salespointframework.useraccount.UserAccountManager
        UserAccountWrapper --> UserAccount
        UserAccountWrapper --> CustomerRepository


    }

    namespace bioladen.event {
        class EntityCreatedEvent {

        }
        EntityCreatedEvent --|> org.salespointframework.context.ApplicationEvent

        EntityCreatedEvent <-- bioladen.useraccount.Customer

    }

    namespace ressources.templates {

        VIEW(register.html) {

        }

        VIEW(login.html) {

        }

        VIEW(userlist.html) {

        }

        VIEW(useracc.html) {

        }

        bioladen.useraccount.UserAccountController --> register.html
        bioladen.useraccount.UserAccountController --> login.html
        bioladen.useraccount.UserAccountController --> userlist.html
        bioladen.useraccount.UserAccountController --> useracc.html
        'bioladen.useraccount.UserAccount --> useracc.html

    }

}





rectangle spring-data-comments-2.1.0.RELEASE.jar as spring {

    package org.springframework.data.repository {
        interface CrudRepository <T, ID> <<Spring>>{
            <S extends T> +save(S) : S
            <S extends T> +saveAll(Iterable<S​>) : Iterable<S>
            +findById(ID) : Optional<T>
            +existsById(ID) : boolean
            +findAll() : Iterable<T>
            +findAllById(Iterable<ID>) : Iterable<T>
            +count() : long
            +deleteById(ID) : void
            +delete(T) : void
            +deleteAll(Iterable<? extends T>) : void
            +deleteAll() : void
        }
    }

}



org.salespointframework.useraccount.UserAccountRepository  *--  org.salespointframework.useraccount.UserAccount
org.salespointframework.useraccount.UserAccountRepository --|> CrudRepository: <<binds>>\n<UserAccount, UserAccountIdentifier>
bioladen.useraccount.UserAccountController "1" --> "1" org.salespointframework.useraccount.UserAccountManager: \n\nUSER_ACCOUNTS
bioladen.useraccount.UserAccountController "1" --> "1" org.salespointframework.useraccount.UserAccountRepository
bioladen.useraccount.UserAccountController --> BusinessTime

bioladen.useraccount.UserAccount --|> org.salespointframework.useraccount.UserAccount

@enduml